---
# file: roles/common/tasks/main.yml

- name: Install aptitude to prevent apt warnings
  apt:
    name: aptitude
    state: present
    update_cache: true
- name: Create internal interface file
  template:
    src: 01-ens4.yaml.j2
    dest: /etc/netplan/01-ens4.yaml
    owner: root
    group: root
    mode: '0644'
  notify: 
    - Apply netplan
- name: Flush handlers
  meta: flush_handlers
