---
# file: roles/kubernetes-worker/tasks/main.yml
- name:  enable net.bridge.bridge-nf-call-iptables
  shell: sysctl net.bridge.bridge-nf-call-iptables=1
  args:
    creates: /proc/sys/net/bridge/bridge-nf-call-iptables
- name: Create /run/flannel/
  file:
    path: /run/flannel/
    state: directory
    mode: '0755'
- name: Create /run/flannel/subnet.env
  template:
    src: subnet.env.j2
    dest: /run/flannel/subnet.env
    owner: root
    group: root
    mode: '0644'
- name: Copy /root/kubeadmin-init-output.txt to worker-1 & worker-2
  copy:
    src: "{{ playbook_dir }}/transfer/kubeadmin-init-output.txt"
    dest: /root/kubeadmin-init-output.txt
- name: Get kubeadmin join command
  shell: "tail -n 2 /root/kubeadmin-init-output.txt"
  register: kubeadm_join_command
- name: Run kubeadmin join
  shell: "{{ kubeadm_join_command.stdout }} --apiserver-advertise-address={{ hostvars[ansible_fqdn]['openstack']['private_v4'] }}"
  args:
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml
