---
# file: roles/docker/tasks/main.yml
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Install basic list of packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','gnupg2','software-properties-common']
    state: present
    update_cache: yes

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker packages
  apt:
    name: ['docker-ce=5:18.09.8~3-0~ubuntu-bionic','docker-ce-cli=5:18.09.8~3-0~ubuntu-bionic','containerd.io']
    state: present

- name: Create docker-daemon.json
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'

- name: Create docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  notify: restart docker
- name: Flush handlers
  meta: flush_handlers
