---
# file: workers.yml
- hosts: workers
  remote_user: ubuntu
  become: true
  become_user: root
  roles:
    - common
    - docker
    - kubeadm
    - kubelet
    - kubectl
    - kubernetes-worker

